name: Build and Release Flatpak-Compose

on:
  push:
    tags:
      - '*'
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: |
          go mod download

      - name: Build flatpak-compose for Linux amd64
        run: |
          GOARCH=amd64 GOOS=linux go build -o flatpak-compose-linux-amd64 ./cmd/main.go

      - name: Build flatpak-compose for Linux arm64
        run: |
          GOARCH=arm64 GOOS=linux go build -o flatpak-compose-linux-arm64 ./cmd/main.go

      - name: Zip artifacts
        run: |
          zip flatpak-compose-linux-amd64.zip flatpak-compose-linux-amd64
          zip flatpak-compose-linux-arm64.zip flatpak-compose-linux-arm64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Linux amd64
        id: upload-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flatpak-compose-linux-amd64.zip
          asset_name: flatpak-compose-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Linux arm64
        id: upload-linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flatpak-compose-linux-arm64.zip
          asset_name: flatpak-compose-linux-arm64.zip
          asset_content_type: application/zip